run formatter
Signed-off-by: Ivan Schaller <ivan@schaller.sh>

diff --git a/shims/pip b/shims/pip
--- a/shims/pip
+++ b/shims/pip
@@ -8,58 +8,58 @@
 set -euo pipefail
 
 this_dir=$(dirname "${BASH_SOURCE[0]}")
-this_dir=$(cd "$this_dir" && pwd -P)  # Normalizes the directory; see https://stackoverflow.com/a/7666/2308068
+this_dir=$(cd "$this_dir" && pwd -P) # Normalizes the directory; see https://stackoverflow.com/a/7666/2308068
 plugin_name=$(basename "$(dirname "$this_dir")")
 
 should_reshim() {
-  if [ "${ASDF_PYTHON_SKIP_RESHIM:-}" ]; then
+    if [ "${ASDF_PYTHON_SKIP_RESHIM:-}" ]; then
+        return 1
+    fi
+
+    for arg; do
+        case "$arg" in
+            install | uninstall)
+                return 0
+                ;;
+        esac
+    done
+
     return 1
-  fi
-
-  for arg; do
-    case "$arg" in
-      install|uninstall)
-        return 0
-      ;;
-    esac
-  done
-
-  return 1
 }
 
 resolve_pip() {
-  local pip_location="${ASDF_PYTHON_CANON_PIP_PATH:-$(search_pip_bin)}"
+    local pip_location="${ASDF_PYTHON_CANON_PIP_PATH:-$(search_pip_bin)}"
 
-  if ! [ "$pip_location" ]; then
-    echo "asdf-python couldn't find a suitable pip executable"
-    echo "This is probably a problem with the plugin, please report this issue"
-    exit 1
-  fi
+    if ! [ "$pip_location" ]; then
+        echo "asdf-python couldn't find a suitable pip executable"
+        echo "This is probably a problem with the plugin, please report this issue"
+        exit 1
+    fi
 
-  echo "$pip_location"
+    echo "$pip_location"
 }
 
 search_pip_bin() {
-  local probably_pip="$(asdf where python)/bin/pip"
+    local probably_pip="$(asdf where python)/bin/pip"
 
-  if [ -x "$probably_pip" ]; then
-    echo "$probably_pip"
-    return 0
-  fi
+    if [ -x "$probably_pip" ]; then
+        echo "$probably_pip"
+        return 0
+    fi
 
-  return 1
+    return 1
 }
 
 wrap_pip() {
-  local pip=$(resolve_pip)
+    local pip=$(resolve_pip)
 
-  if should_reshim "$@"; then
-    "$pip" "$@"
-    echo "Reshimming asdf $plugin_name..."
-    asdf reshim "$plugin_name"
-  else
-    exec "$pip" "$@"
-  fi
+    if should_reshim "$@"; then
+        "$pip" "$@"
+        echo "Reshimming asdf $plugin_name..."
+        asdf reshim "$plugin_name"
+    else
+        exec "$pip" "$@"
+    fi
 }
 
 wrap_pip "$@"
